source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '9.0'
use_frameworks!
target 'TestKitchen' do
	pod 'Alamofire', '~> 3.4'
	pod 'Kingfisher', '~> 2.4'
	pod 'XWSwiftRefresh', '~> 0.1.9' 
	pod 'SnapKit', '~> 0.15.0'
end

